### ISSUE TITLE
Make hrp2-dynamics optional

### ISSUE THREAD

**Issue by thomas-moulard** [jrl-umi3218/jrl-walkgen#1]
The closed source package hrp2-dynamics should be optional.

It prevents Debian package compilation from succeding:
Cf http://launchpadlibrarian.net/57086468/buildlog_ubuntu-lucid-i386.jrl-walkgen_1.0.0.99-3_FAILEDTOBUILD.txt.gz

Tests should return 77 if hrp2-dynamic is not found.

**Comment by olivier-stasse** [comment]
Hi Thomas,
thanks for pointing out this problem.
 Commit 1a5f1 should fix the matter.
However, the tests should still work even without hrp2-dynamics as it
is really optional, so I did not return 77.
Could you confirm that the new commit is coherent before I close the issue ?

**Comment by thomas-moulard** [comment]
Compiles now with commid b6dc90fa9cf380c0a46d1bc0dd0f4fd3cb818af7

**Comment by thomas-moulard** [comment]
Package now fallbacks to jrl-dynamics properly, no tests have to be disabled.
Closing issue.
