### ISSUE TITLE
Pushing topic/python into master.

### ISSUE THREAD

**Issue by olivier-stasse** [jrl-umi3218/jrl-walkgen#12]
Dear all,
I finally had sometime to test the pattern generator in the python environment.
If this is fine with you, I would like to push topic/python in the master.

I guess giving the current activity that nobody will have a problem with that.
Best,
Olivier.

**Comment by thomas-moulard** [comment]
@olivier-stasse Can you do that and close the ticket at the same time (please mention close #12 somewhere in the commit message to link the commit with this ticket resolution). Thanks!

**Comment by olivier-stasse** [comment]
topic/python do no exist any more.
