### ISSUE TITLE
Config files to run TestFootPrintPGInterface

### ISSUE THREAD

**Issue by DavidB-UQ** [jrl-umi3218/jrl-walkgen#13]
Hi

I got everything installed.  I should put my notes online somewhere, the linking process for LAPACK/CLAPACK/gfortran was a bit tricky.

I am trying to run 'TestFootPrintPGInterface' but it does not execute correctly.
- It would be very helpful if this package included demo wrl/xml files to execute this test?
- What are the important relationships been the files 'MyModel.wrl', 'Specificities.xml' and 'LinkJointRank.xml' ?
  Which joint names, link names, or the mother-child relationship is important?
- The tests 'TestHerdt2010' and 'TestMorisawa2007' have been automatically compiled. Should 'TestKajita2003' also execute?

Thankyou for your help. I've included more info below.

.......

1)
I found a set of the wrl/xml files in 'jrl-dynamics/unitTesting' and 'jrl-sample-humanoid-robot'.

I can run 'TestFootPrintPGInterface' but the output is not correct, maybe because this robot's DOF do not match the code. 

The code tries to set the joint angles in the order legs->chest->head->arms but this model does not match.

.

2)
Then I found missing files 'HRP2LinkJointRank.xml' and 'HRP2Specificities.xml' from
here 
ftp://softs.laas.fr/pub/openrobots/hrp2_14/
and modified the sample.wrl to have all the same DOF.

But 'TestFootPrintPGInterface' segfaults when reading the VRML file, 
in void DynMultiBodyPrivate::SpecifyTheRootLabel(int ID)
while doing  m_listOfBodies[ID]->setLabelMother(-1);   for ID=0

There must be something in the structure between *.wrl <--> *.xml that I have broken.

**Comment by DavidB-UQ** [comment]
Update, here is some things I found:

LinkJointRank.xml
- It seems that Rank numbers 1-5 are hidden, and make up the 6 DOF for the floating WAIST joint.
- Other rank numbers must be sequential
- The "Nb" tag should be the number of ?, but it does not seem to be critical

model.wrl
- Bug 1:  Joints of type "fixed" are not parsable, and cause many strange behavior. Therefore an un-wanted joint must be completely removed from the model.
- Bug 2: When editing a model with OpenHRP, it can add fields that cause the SpiritVRML reader to not detect all the bodies
  So far, removing the following tags makes it detect 6 joints/bodies in my new model, instead of zero!
                  ulimit [0.0 0.0 ]
                  llimit [0.0 0.0 ]
                  uvlimit [0.0 0.0 ]
                  lvlimit [0.0 0.0 ]

Now I need to find what other tags are causing it to fail parsing the rest of the model...

I'm still unsure if there is a relationship between JointID in the model, and the joint vector IDs in the walk generator...

**Comment by olivier-stasse** [comment]
Hi David,
For LinkJointRank.xml, we assume that the root joint is a free flyer and then has 6 degree of freedoms (DOFs).
The number of DOFs depends upon the type of the joints.
The role of LinkJointRank is to map the vector state created internally by jrl-dynamics following a depth-first-exploration of the kinematic tree to a different mapping. Most of the humanoid robot are using a joint of type rotation -> 1 DOF. 

Model.wrl is relying on jrl-dynamics to read a robot VRML file. We do not have fixed joint as in ROS mostly for computational reason. The spirit VRML reader is not fully supporting the VRML standard, just a subset of the OpenHRP grammar.

**Comment by DavidB-UQ** [comment]
Thankyou.
I figured out how to make the VRML Reader accept my model.
- What is the implied order that the program expects the joints?
         Could you tell me the order of the kinematic chains please?

Initial Pose Half-sitting:
    0.0, 0.0, -26.0, 50.0, -24.0, 0.0, 0.0, 0.0, -26.0, 50.0, -24.0, 0.0,  // legs
    0.0, 0.0, -23.7, 6.6, // chest and head
    27.0, -5.0, -4.0, -87.0, -4.0, -16.0, 20.0, // right arm
    15.0,  10.0, 0.0, -20.0, 0.0, 0.0, 10.0, // left arm 
    -20.0, 20.0, -20.0, 20.0, -20.0, // right hand
    -10.0, 10.0, -10.0, 10.0, -10.0  // left hand

e.g.

Hip Roll or Pitch -> Roll or Pitch -> Hip Yaw -> Knee Pitch -> Ankle Pitch -> Ankle Roll

Waist Pitch or Yaw -> Waist Pitch or Yaw  ...  Head Pitch or Yaw -> Head Pitch or Yaw

Shoulder Roll or Pitch or Yaw  -> Shoulder Roll or Pitch or Yaw  -> Shoulder Roll or Pitch or Yaw  -> Elbow -> Wrist Roll or Pitch or Yaw -> Wrist Roll or Pitch or Yaw -> Wrist Roll or Pitch or Yaw

Thanks.

**Comment by DavidB-UQ** [comment]
Hi, I see now that the Kajita plugin is dependent on closed-source packages.  
- What sort of information is it dependent on?
- Do you recall what parts need to be separated?

Thankyou.

**Comment by olivier-stasse** [comment]
>   What is the implied order that the program expects the joints? Could you tell me the order of the kinematic >chains please?
> 
> Initial Pose Half-sitting:
> 0.0, 0.0, -26.0, 50.0, -24.0, 0.0, 0.0, 0.0, -26.0, 50.0, -24.0, 0.0, // legs
> 0.0, 0.0, -23.7, 6.6, // chest and head
> 27.0, -5.0, -4.0, -87.0, -4.0, -16.0, 20.0, // right arm
> 15.0, 10.0, 0.0, -20.0, 0.0, 0.0, 10.0, // left arm
> -20.0, 20.0, -20.0, 20.0, -20.0, // right hand
> -10.0, 10.0, -10.0, 10.0, -10.0 // left hand
> 
> e.g.
> 
> Hip Roll or Pitch -> Roll or Pitch -> Hip Yaw -> Knee Pitch -> Ankle Pitch -> Ankle Roll
> 
> Waist Pitch or Yaw -> Waist Pitch or Yaw ... Head Pitch or Yaw -> Head Pitch or Yaw
> 
> Shoulder Roll or Pitch or Yaw -> Shoulder Roll or Pitch or Yaw -> Shoulder Roll or Pitch or Yaw -> Elbow -> >Wrist |Roll or Pitch or Yaw -> Wrist Roll or Pitch or Yaw -> Wrist Roll or Pitch or Yaw

In jrl-dynamics you will find a file called sample.wrl which is a free model provided by OpenHRP.
You will also find three files:
sampleInitConfig.dat (which is a neutral position for starting to walk)
sampleLinkJointRank.xml which relates the index in the kinematic tree and the robot state vector.
sampleSpecificities.xml which map some semantics on the wrl file (head, feet, hands. etc...)

I suggest that you go through those files to have a better understanding on how the 
kinematic tree and the control for actuation are realized.

**Comment by olivier-stasse** [comment]
> Hi, I see now that the Kajita plugin is dependent on closed-source packages.
> 
>   What sort of information is it dependent on?
> 
>    Do you recall what parts need to be separated?
> 
> Thankyou.

The only reason why it is closed, is that to implement the dynamic filter of Kajita,
you need to compute the IK of the robot, then to recompute RNEA.

We implemented an analytical solution for our robot (which is closed) and did not port it to sample.wrl.

If you can derive the method 

virtual bool getSpecializedInverseKinematics(const CjrlJoint & jointRoot,
                         const CjrlJoint & jointEnd,
                         const matrix4d & jointRootPosition,
                         const matrix4d & jointEndPosition,
                         vectorN &q)
then you can use Kajita.

**Comment by DavidB-UQ** [comment]
Hi again,
I did managed to implement getSpecializedInverseKinematics().

I noticed that some code was written to potentially enable both single stage and double stage versions of Kajita's algorithm.
The option to load single stage Kajita was commented out, so only double stage could be used.

I have tried to modify things to finish the single stage version of Kajita but I cannot get it to work.
- Do you recall please what needs to be completed to separate the first stage from the second stage?

**Comment by olivier-stasse** [comment]
Hi David,
Sorry for taking some much time to answer.

But this might of some interest for other people.
To have only the first stage please use:
aPGI.ParseCmd(":SetAlgoForZmpTrajectory KajitaOneStage");

It is activated here:
https://github.com/jrl-umi3218/jrl-walkgen/blob/master/src/GlobalStrategyManagers/DoubleStagePreviewControlStrategy.cpp#L243
