### ISSUE TITLE
TestKajita2003 is failing

### ISSUE THREAD

**Issue by thomas-moulard** [jrl-umi3218/jrl-walkgen#15]
TestKajita2003 is failing.
This test has been disabled in commit ff510e5c7e6c5a11c52a0a5196d64c77fa4a26d6.

**Comment by olivier-stasse** [comment]
Hi Thomas, 
I hope that Travis will be happy with commit 68d85.

**Comment by olivier-stasse** [comment]
Travis is happy. Can I close the issue ?

**Comment by thomas-moulard** [comment]
If Travis is happy, I am too ;) Closing.
