### ISSUE TITLE
Make install is failing due to the lack of package.dox file

### ISSUE THREAD

**Issue by thomas-moulard** [jrl-umi3218/jrl-walkgen#2]
`make install` fails as the doc cannot be generated.

```
[ 98%] documentation
cd /home/tmoulard/profiles/default-i386-linux-ubuntu-8.04/src/unstable/jrl/jrl-walkgen/_build/doc && /usr/bin/doxygen package.dox
Error: configuration file package.dox not found!
Doxygen version 1.5.5
Copyright Dimitri van Heesch 1997-2008
```

**Comment by olivier-stasse** [comment]
Could you substantiate the problem, buildbot is not complaining ...
For instance tonight this specific line is working without any problem:
https://jrlserver.muse.aist.go.jp/buildbot/builders/walkGenJrl-jrlmt-master/builds/430/steps/compile/logs/stdio

**Comment by thomas-moulard** [comment]
Could you confirm that -DGENERATE_DOC is passed by buildbot?
If not, of course the problem won't appear if not :)

(BTW it would be very interesting to log the CMakeCache so that I can see this kind of thing directly from the web interface)

**Comment by thomas-moulard** [comment]
My bad, seems like it is working with 15e3238110b02aa2ee804f75fbc27de477afe277.

Closing.
