### ISSUE TITLE
Error in linking tests of jrl-walkgen

### ISSUE THREAD

**Issue by fbleibel** [jrl-umi3218/jrl-walkgen#4]
I have the following undefined symbols after linking jrl-walkgen:

$ ld jrl-walkgen/ubuild/DEBUG/src/libjrl-walkgen.so
ld: warning: cannot find entry symbol _start; not setting start address
jrl-walkgen/ubuild/DEBUG/src/libjrl-walkgen.so: undefined reference to `dgges_'
jrl-walkgen/ubuild/DEBUG/src/libjrl-walkgen.so: undefined reference to `dgesvx_'
jrl-walkgen/ubuild/DEBUG/src/libjrl-walkgen.so: undefined reference to`dgetrf_'
jrl-walkgen/ubuild/DEBUG/src/libjrl-walkgen.so: undefined reference to `dlapy2_'
jrl-walkgen/ubuild/DEBUG/src/libjrl-walkgen.so: undefined reference to`dlamch_'
jrl-walkgen/ubuild/DEBUG/src/libjrl-walkgen.so: undefined reference to `dgesvd_'

**Comment by andrei-herdt** [comment]
Me too:
OptimalControllerSolver.cpp:(.text+0x1b43): undefined reference to `dgesvd_'

**Comment by fbleibel** [comment]
I added the link flags and detection of lapack libraries. It should work now.

**Comment by thomas-moulard** [comment]
Sorry about that.
This should be definitively fixed by 4179c0fdcc67b97ba882bac846f29b3e794d011d.

Please re-open if it does not work on your machine.
