### ISSUE TITLE
Compile and link flags

### ISSUE THREAD

**Issue by francois-keith** [jrl-umi3218/jrl-walkgen#5]
I have some issues with the compilation and link flags with the jrl-walkgen project

The main compilation issue is that the path to boost-include-dir is missing.
This is due to the line 
INCLUDE_DIRECTORIES(${JRL_MAL_INCLUDEDIR})
I'll suggest to use instead (as in other packages)
ADD_DEFINITIONS(${JRL_MAL_CFLAGS})
to patch this issue.

Concerning the Link_Flags, there is two problems
1\ There is no link for the main project (jrl-walkgenjl)

2\ a windows specific issue, due to pkg-config:
The separation between Libraries_dir and Libraries is not properly done, and the macros
JRL_DYNAMICS_LIBRARIES and JRL_DYNAMICS_LIBRARY_DIRS are unusable

The previously adopted solution was to use directly the command
IF(WIN32)
SET_TARGET_PROPERTIES( compiled_lib PROPERTIES LINK_FLAGS "${JRL_DYNAMICS_LDFLAGS}")
ENDIF(WIN32)
I'd like to reintroduce it in the CMake files, may I?

**Comment by thomas-moulard** [comment]
This should be fixed by 4179c0fdcc67b97ba882bac846f29b3e794d011d.

Please re-open if this patch is not enough.
