### ISSUE TITLE
unit tests: files not found

### ISSUE THREAD

**Issue by francois-keith** [jrl-umi3218/jrl-walkgen#6]
The files used for the unit tests (sample*.xml) are those used and installed by the project jrl-dynamics. These files, installed in $INSTALL_FOLDER/share/jrl/dynamics/examples, are wrongly researched in the folder $INSTALL_FOLDER/examples

I think that the error is due to the field datarootdir of the file jrl-dynamics.pc, that is incorrect ("jrl/dynamics/" is missing), rather than a error in jrl-walkgen. 
Can anyone confirm that?

**Comment by olivier-stasse** [comment]
Fixed with a patch on jrl-dynamics.
