### ISSUE TITLE
Compliation failure with MSVS80

### ISSUE THREAD

**Issue by mehdi-benallegue** [jrl-umi3218/jrl-walkgen#7]
Hello 

The build fails with the following error message :
        2>......\tests\TestObject.cpp(45) : error C3861: 'trunc' : identifier not found

I couldn't find `trunc` in the specifivations of  `<cmath>` or `<math.h>` on VS80
http://msdn.microsoft.com/en-us/library/7wsh95e5%28VS.80%29.aspx

As I am not confident about what exactly does this function
        double TestSuite::filterprecision(double adb)

I need to ask you if it is equivalent to remplace `trunc` by `floor` (or `ceil` or `round`) which is supported.

Thank you in advance.

**Comment by thomas-moulard** [comment]
See "man trunc": http://linux.die.net/man/3/trunc

The best solution to handle these portability problems is to write src/portability/trunc.cpp and src/portability/trunc.hh to implement a portable version of trunc (i.e. if Linux do nothing and implement for Windows a trunc function whose behavior matches the man page).

Gnulib provides an implementation of trunc to workaround portability issues, see: http://www.mail-archive.com/bug-gnulib@gnu.org/msg07966.html

Please _DO NOT_ copy it into jrl-walkgen before checking that licenses are compatible. _If_ the licenses are compatible, do not forget to change the documentation to reflect that jrl-walkgen now contains part of gnulib.

Sorry for not being able to do the checks myself but it is quite late in France ;)

**Comment by mehdi-benallegue** [comment]
Thank you very much for the quick (but late ^^ ) answer, 

The license is LGPL, so it is compatible. I will put this in my todo list with high priority.

I close the issue.
Thank you.

Mehdi.
