### ISSUE TITLE
Suspect memory access.

### ISSUE THREAD

**Issue by francois-keith** [jrl-umi3218/jrl-walkgen#9]
This error has been observed in the branch topic/rc-v3.1.4 (but has not been observed in the branch master)

I think there is a issue in
src/ZMPRefTrajectoryGeneration/generator-vel-ref.cpp

There is a suspect memory access to a deque at line 298: we want to access to the 1st or 2nd element whereas the deque is empty.

This can be observed by adding the following lines just before:
-         if( PrwSupport.StateChanged && PrwSupport.StepNumber>0
-               && PreviewedSupportAngles.size() == 0)
-                 std::cout << " Empty deque, but access to " << (PrwSupport.StepNumber-1) <<std::endl;

This code is used for example when using TestHerdt.
Oddly, it does not crash on MacOSX systems, but it crashes on Win32 systems.

**Comment by andrei-herdt** [comment]
Should be ok now. 
I let you verify and close?

**Comment by francois-keith** [comment]
Well done.
